
package Crunch.utilidades;


public enum Rubro {
      
    ALMACEN,VERDULERIA,CARNICERIA,GOMERIA,LUBRICENTRO,ELECTRONICA,COMPUTACION,MECANICA,FERRETERIA,TINTURERIA,ROTISERIA,PELUQUERIA,LIBRERIA,DIETETICA,
    LIMPIEZA,PERFUMERIA,FRAMACIA,PETSHOP,VETERINARIA,PANADERIA,POLLERIA,INDUMENTARIA
}
